### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by jem890** [JohnKimDev/sails-hook-req-validate#6]
Hi, I use sails 0.12.14, which version of sails-hook-req-validate should I use? Can I use version 2.7.1? If not, which one would you recommend?

Thanks in advance.

**Comment by jem890** [comment]
Hi @JohnKimDev, could you help me please?

Many thanks

**Comment by JohnKimDev** [comment]
Since there is a dependency, this library doesn't work with sails < 1.0.0, Sorry.

**Comment by jem890** [comment]
Thanks! 

Is there any version that used to work with sails 0.12?
